// Starter vocabulary — Al-Arabiyyah Bayna Yadayk, Book 1, Units 1.1 & 1.2
// Demo set. Spot-check harakat and unit placement against your own copy of the book.
// To add words: copy a line and change the fields. id must stay unique.
const VOCAB = [
  { id: 1,  ar: "السَّلامُ عَلَيْكُم", en: "peace be upon you",   tr: "as-salāmu ʿalaykum", unit: "1.1" },
  { id: 2,  ar: "مَرْحَبًا",            en: "hello",               tr: "marḥaban",          unit: "1.1" },
  { id: 3,  ar: "أَهْلاً وَسَهْلاً",     en: "welcome",             tr: "ahlan wa sahlan",   unit: "1.1" },
  { id: 4,  ar: "صَبَاحُ الخَيْر",       en: "good morning",        tr: "ṣabāḥu l-khayr",    unit: "1.1" },
  { id: 5,  ar: "مَسَاءُ الخَيْر",       en: "good evening",        tr: "masāʾu l-khayr",    unit: "1.1" },
  { id: 6,  ar: "كَيْفَ الحَال؟",        en: "how are you?",        tr: "kayfa l-ḥāl",       unit: "1.1" },
  { id: 7,  ar: "بِخَيْر",              en: "fine / well",         tr: "bi-khayr",          unit: "1.1" },
  { id: 8,  ar: "الحَمْدُ لِله",         en: "praise be to God",    tr: "al-ḥamdu lillāh",   unit: "1.1" },
  { id: 9,  ar: "شُكْرًا",              en: "thank you",           tr: "shukran",           unit: "1.1" },
  { id: 10, ar: "مَعَ السَّلامَة",       en: "goodbye",             tr: "maʿa s-salāma",     unit: "1.1" },
  { id: 11, ar: "اِسْم",               en: "name",                tr: "ism",               unit: "1.1" },
  { id: 12, ar: "مَا اسْمُكَ؟",          en: "what is your name?",  tr: "mā smuka",          unit: "1.1" },
  { id: 13, ar: "أَنَا",               en: "I / me",              tr: "anā",               unit: "1.1" },
  { id: 14, ar: "أَنْتَ",              en: "you (m)",             tr: "anta",              unit: "1.1" },
  { id: 15, ar: "أَنْتِ",              en: "you (f)",             tr: "anti",              unit: "1.1" },
  { id: 16, ar: "مِنْ أَيْنَ؟",          en: "where from?",         tr: "min ayna",          unit: "1.2" },
  { id: 17, ar: "بَلَد",               en: "country",             tr: "balad",             unit: "1.2" },
  { id: 18, ar: "مَدِينَة",             en: "city",                tr: "madīna",            unit: "1.2" },
  { id: 19, ar: "طَالِب",              en: "student (m)",         tr: "ṭālib",             unit: "1.2" },
  { id: 20, ar: "طَالِبَة",             en: "student (f)",         tr: "ṭāliba",            unit: "1.2" },
  { id: 21, ar: "مُدَرِّس",             en: "teacher",             tr: "mudarris",          unit: "1.2" },
  { id: 22, ar: "صَدِيق",              en: "friend",              tr: "ṣadīq",             unit: "1.2" },
  { id: 23, ar: "أَخ",                 en: "brother",             tr: "akh",               unit: "1.2" },
  { id: 24, ar: "أُخْت",               en: "sister",              tr: "ukht",              unit: "1.2" },
  { id: 25, ar: "مُسْلِم",              en: "Muslim",              tr: "muslim",            unit: "1.2" },
  { id: 26, ar: "وَاحِد",              en: "one",                 tr: "wāḥid",             unit: "1.2" },
  { id: 27, ar: "اِثْنَان",             en: "two",                 tr: "ithnān",            unit: "1.2" },
  { id: 28, ar: "ثَلاثَة",             en: "three",               tr: "thalātha",          unit: "1.2" },
  { id: 29, ar: "أَرْبَعَة",            en: "four",                tr: "arbaʿa",            unit: "1.2" },
  { id: 30, ar: "خَمْسَة",              en: "five",                tr: "khamsa",            unit: "1.2" },
];
